services:
  opendots:
    build: .
    ports:
      - "127.0.0.1:8765:8765"
    volumes:
      - ./.opendots:/app/.opendots
      - ./examples/workspaces:/app/examples/workspaces
    init: true
    stop_grace_period: 240s
